import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const core = stripExports(fs.readFileSync(path.join(root, "src/core.js"), "utf8"));
const storage = stripImports(stripExports(fs.readFileSync(path.join(root, "src/storage.js"), "utf8")));
const app = stripImports(fs.readFileSync(path.join(root, "src/app.js"), "utf8"));

const bundle = `// Generated by scripts/build-browser.js.
// This file lets index.html run directly from file:// without ES module imports.
(() => {
${indent(core)}

${indent(storage)}

${indent(app)}
})();
`;

fs.writeFileSync(path.join(root, "src/focus-ledger.bundle.js"), bundle);

function stripExports(source) {
  return source.replace(/^export\s+/gm, "");
}

function stripImports(source) {
  return source.replace(/^import[\s\S]*?;\n\n/gm, "");
}

function indent(source) {
  return source
    .trim()
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
}

